name: Run weather daily

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  
  schedule:
    - cron: '0 10 * * *' # This will run at 10 AM UTC every day

jobs:
  collect-weather-data:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Step 2: Set up permissions for the script
    - name: Make script executable
      run: chmod +x weather.sh
    
    # Step 3: Set up Git configuration (necessary for commit and push)
    - name: Set up Git
      run: |
       git config user.name "github-actions[bot]"
       git config user.email "github-actions[bot]@users.noreply.github.com"

    # Step 4: Run the weather.sh script
    - name: Run weather.sh script
      run: |
       chmod +x weather.sh
       ./weather.sh

    # Step 5: Commit and push changes back to the repository
    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the GitHub token stored as a secret
      run: |
        git add data/weather/
        git commit -m "Update weather daily"
        git push 