name: Run weather daily

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  
  schedule:
    - cron: '0 10 * * *' # This will run at 10 AM UTC every day

jobs:
  collect-weather-data:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Step 2: Set up permissions for the script
    - name: Make script executable
      run: chmod +x weather.sh
    
    # Set up Git configuration (necessary for commit and push)
    - name: Set up Git
      run: |
       git config user.name "github-actions"
       git config user.email "github-actions@github.com"

    # Run the weather.sh script
    - name: Run weather.sh script
      run: |
       chmod +x weather.sh
       ./weather.sh

 # Commit and push changes back to the repository
    - name: Commit and push changes
      run: |
       git add data/weather/
       git commit -m "Update weather data"
       git push