name: Run weather daily

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  collect-weather-data:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Step 2: Set up permissions for the script
    - name: Make script executable
      run: chmod +x weather.sh
    
    # Step 3: Run the weather script
    - name: Collect Weather Data
      run: ./weather.sh
    
    # Step 4: Configure git user for committing
    - name: Configure Git
      run: |
        git config user.name "Grainne10"
        git config user.email "<G00218690@atu.ie>"